// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XTracker.Context;

#nullable disable

namespace XTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240318010902_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("XTracker.Models.Habits.Day", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Days");
                });

            modelBuilder.Entity("XTracker.Models.Habits.DayHabit", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("DayId")
                        .HasColumnType("int");

                    b.Property<int?>("HabitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("HabitId");

                    b.ToTable("DayHabits");
                });

            modelBuilder.Entity("XTracker.Models.Habits.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("XTracker.Models.Habits.HabitWeekDay", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("HabitId")
                        .HasColumnType("int");

                    b.Property<int?>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("HabitWeekDays");
                });

            modelBuilder.Entity("XTracker.Models.Habits.DayHabit", b =>
                {
                    b.HasOne("XTracker.Models.Habits.Day", "Day")
                        .WithMany("DayHabits")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("XTracker.Models.Habits.Habit", "Habit")
                        .WithMany("DayHabits")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Day");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("XTracker.Models.Habits.HabitWeekDay", b =>
                {
                    b.HasOne("XTracker.Models.Habits.Habit", "Habit")
                        .WithMany("WeekDays")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("XTracker.Models.Habits.Day", b =>
                {
                    b.Navigation("DayHabits");
                });

            modelBuilder.Entity("XTracker.Models.Habits.Habit", b =>
                {
                    b.Navigation("DayHabits");

                    b.Navigation("WeekDays");
                });
#pragma warning restore 612, 618
        }
    }
}
